package main

import (
	"PortalClient/configs"
	"PortalClient/internal/middleware"
	"PortalClient/internal/routes"
	"net/http"
	"time"

	_ "PortalClient/docs" // docs is generated by Swag CLI

	"github.com/gorilla/mux"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Orders API
// @version 1.0
// @description This is a sample serice for managing orders
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email soberkoder@swagger.io
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8000
// @BasePath /
func init() {
	// Initialize config file
	configs.InitConfigFile()

	environment := viper.GetString("Environment")
	if environment != "Development" {
		log.SetFormatter(&log.JSONFormatter{})
	}

	// Initialize tracer
	configs.InitTracer()
}

func main() {
	// route handler
	router := mux.NewRouter().StrictSlash(true)
	router.Use(middleware.LoggingMiddleware)
	routes.HandleRoutes(router)

	// Swagger UI
	router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)

	// Create and start server
	log.Info("PortalClient starting")
	srv := &http.Server{
		Handler: router,
		Addr:    ":8000",
		// Good practice to set timeouts to avoid Slowloris attacks.
		WriteTimeout: time.Second * 15,
		ReadTimeout:  time.Second * 15,
		IdleTimeout:  time.Second * 60,
	}
	log.Fatal(srv.ListenAndServe())

	// Close tracer
	configs.CloseTracer()
}
